version: '3.6'

networks:
   rl-network:
      name: "rl-network"
      driver: "bridge"

services:
   rl-postgres:
      image: rl-postgres:${RL_VERSION}
      container_name: rl-postgres
      hostname: rl-postgres
      tty: true
      stdin_open: true
      restart: always
      networks:
         - rl-network
      env_file:
         - ./postgres/postgres.env
      ports:
         - 5432:5432
   
   rl-redis:
      image: rl-redis:${RL_VERSION}
      container_name: rl-redis
      hostname: rl-redis
      tty: true
      stdin_open: true
      restart: always
      networks:
         - rl-network
   
   rl-collector:
      image: rl-collector:${RL_VERSION}
      container_name: rl-collector
      hostname: rl-collector
      tty: true
      stdin_open: true
      restart: always
      networks:
         - rl-network
      env_file:
         - ./collector/collector.env

   rl-apisvr:
      image: rl-apisvr:${RL_VERSION}
      container_name: rl-apisvr
      hostname: rl-apisvr
      tty: true
      stdin_open: true
      restart: always
      networks:
         - rl-network
      ports:
         - 8080:8080
      env_file:
         - ./apisvr/apisvr.env
