#!/bin/bash
#
# This script packages the following into a tar.gz
#    build/riverlife.tar.gz
#    exec.sh
#    im_run
#    im_install
#

source version
source globals

DOCKER_IMAGES="sudo docker images"
LOADED_RL_IMAGES="$DOCKER_IMAGES | grep rl- | awk '{print \$1,\$2}' OFS=':' "

echo -e "--------------------------------------------------"
echo -e "- Removing old River Life images..."
echo -e "--------------------------------------------------"
for rl_image in $(eval $LOADED_RL_IMAGES);do
   echo -e "Removing ${rl_image} ..."
   sudo docker rmi ${rl_image}
   echo ""
done

echo -e "--------------------------------------------------"
echo -e "- Loading River Life images..."
echo -e "--------------------------------------------------"
for rl_image in ${PKG_LOCATION}/*/*.image;do
   echo "Loading ${rl_image} ..."
   sudo docker load < ${rl_image}
   echo ""
done

echo -e "\nInstall Completed."